name = "MAFFT"
uuid = "a53cae88-8244-4411-9f7a-2be6f2b6aa6d"
authors = ["Michael Persico <michael.a.persico@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
