name = "MAFFT"
uuid = "a53cae88-8244-4411-9f7a-2be6f2b6aa6d"
authors = ["Michael Persico <michael.a.persico@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
BioAlignments = "00701ae9-d1dc-5365-b64a-a3a3ebf5695e"
BioSequences = "7e6ae17a-c86d-528c-b3b9-7f778a29fe59"
FASTX = "c2308a5c-f048-11e8-3e8a-31650f418d12"
MAFFT_jll = "72a4bdf2-be5e-5c84-b157-f1dc2927f791"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[compat]
BioAlignments = "3"
BioSequences = "3"
FASTX = "2"
MAFFT_jll = "7"
julia = "1.6"
